# Generated by Django 5.2.3 on 2025-06-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_submission', '0006_formsession_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('op_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('op_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('op_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_info', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='form_submission.formsession')),
            ],
        ),
    ]
