# Generated by Django 5.2.1 on 2025-06-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("email_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("current_step", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_session",
                        to="email_management.formtoken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("property_address", models.TextField(blank=True, null=True)),
                (
                    "property_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "property_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bill_to_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "property_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reservation_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "property_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("property_website", models.URLField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_details",
                        to="form_submission.formsession",
                    ),
                ),
            ],
        ),
    ]
