# Generated by Django 5.2.3 on 2025-06-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_submission', '0004_websitedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydetails',
            name='form_session',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='gallery_details',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='form_session',
        ),
        migrations.RemoveField(
            model_name='websitedetails',
            name='form_session',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.DeleteModel(
            name='GalleryDetails',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.DeleteModel(
            name='PropertyDetails',
        ),
        migrations.DeleteModel(
            name='WebsiteDetails',
        ),
    ]
