# Generated by Django 5.2.3 on 2025-06-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_remove_formtoken_used_at'),
        ('form_submission', '0005_remove_gallerydetails_form_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsession',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='form_session_category', to='email_management.categories'),
            preserve_default=False,
        ),
    ]
