# Generated by Django 5.2.3 on 2025-06-26 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_submission', '0006_formsession_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_links', models.CharField(blank=True, max_length=255, null=True)),
                ('ambience_links', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities_links', models.CharField(blank=True, max_length=255, null=True)),
                ('other_links', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_details', to='form_submission.formsession')),
            ],
        ),
    ]
