# Generated by Django 5.2.3 on 2025-06-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_submission', '0006_formsession_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, max_length=255, null=True)),
                ('occupancy', models.CharField(blank=True, max_length=255, null=True)),
                ('room_price', models.CharField(blank=True, max_length=255, null=True)),
                ('room_image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('room_additional_info', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='form_submission.formsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
