# Generated by Django 5.2.3 on 2025-06-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_submission', '0005_remove_gallerydetails_form_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.TextField()),
                ('property_city', models.CharField(max_length=100)),
                ('property_state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('property_country', models.CharField(max_length=100)),
                ('bill_to_company', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=50)),
                ('property_phone', models.CharField(max_length=20)),
                ('reservation_phone', models.CharField(max_length=20)),
                ('property_email', models.EmailField(max_length=254)),
                ('property_website', models.URLField()),
                ('base_currency', models.CharField(max_length=50)),
                ('no_of_rooms', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('property_category', models.CharField(max_length=50)),
                ('star_category', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('additional_info', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='form_submission.formsession')),
            ],
        ),
    ]
