# Generated by Django 5.2.3 on 2025-06-25 04:57

import django.core.validators
import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True)),
                ('client_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('client_name', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_management.categories')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
