# Generated by Django 5.2.3 on 2025-06-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtoken',
            name='used_at',
        ),
    ]
