# Generated by Django 5.2.3 on 2025-06-24 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtoken',
            name='client_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formtoken',
            name='client_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
