# Generated by Django 5.2.1 on 2025-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_management", "0002_client_delete_emailinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
