# Generated by Django 5.2.3 on 2025-06-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_submission', '0006_formsession_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('website_name', models.CharField(blank=True, max_length=255, null=True)),
                ('about_us_content', models.TextField(blank=True, null=True)),
                ('additional_content', models.TextField(blank=True, null=True)),
                ('near_by', models.TextField(blank=True, null=True)),
                ('domain_url', models.URLField(blank=True, null=True)),
                ('domain_password', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_username', models.CharField(blank=True, max_length=255, null=True)),
                ('existing_website_link', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_details', to='form_submission.formsession')),
            ],
        ),
    ]
